#!/usr/bin/python3
import sys, time

class ExceBox:
    def __init__(self):
        pass

class Logger:
    def __init__(self, ip, port, logfile):
        self.logfile = open(logfile, 'w')
        self.ip = ip
        self.port = port
        #TODO: init executor class with sandbox

    def run_tests(self, testcase_dir):
        pass

    def _write_result(self, exitcode):
        stat = "up" if exitcode == 0 else "down"
        row = "{}, {}, {}, {}\n".format(\
                int(time.time()), self.ip, self.port, stat)
        self.logfile.write(row)

if __name__ == '__main__':
    if len(sys.argv) < 5:
        print("%s [ip addr] [port] [testcase dir] [logfile]" % sys.argv[0])
        exit()
